### ISSUE TITLE
Allow strings as description for `describe` blocks

### ISSUE THREAD

**Issue by utkarshkukreti** [reem/stainless#11]
It'd be really nice if `describe` supports long descriptions like `it` does. We could do the same renaming that `it` blocks currently do to make the description a valid identifier and use it as the `mod` name.

I'm willing to implement this if you think this is a good idea, let me know!

**Comment by ujh** [comment]
I'll close this issue as I believe it's a feature that's not going to be supported any time soon by the rust compiler.
