### ISSUE TITLE
Use BDD semantics

### ISSUE THREAD

**Issue by ihrwein** [reem/stainless#25]
First of all thanks for this awesome work!

I came accross your crate during searching for a BDD (Behavior Driven Development) framework for Rust. When I saw the `before_each`, `after_each` and `it` subblocks I thought there is a close relation between them and their BDD counterparts:

* `before_each` == `given` (precondition)
* `it` == `when` (a trigger)
* `after_each` == `then` (postcondition) 

I think it would be nice to access to these subblocks with their BDD names.

**Comment by reem** [comment]
Adding aliases is pretty easy, if that's all you're asking for.

**Comment by ihrwein** [comment]
Yeah!

Thank you very much :)
