### ISSUE TITLE
Add separate lexical scope for the actual test

### ISSUE THREAD

**Issue by ujh** [reem/stainless#35]
Assuming the following test:

``` rust
before_each {
    let mut interpreter = GTPInterpreter::new(config.clone(), engine);
}

after_each {
    interpreter.quit();
}

it "empty string" {
    let response = interpreter.read("");
    assert!(response.is_err());
    assert_that(response.unwrap_err(), is(equal_to("empty command")));
}
```

where the `read` is defined as follows: `pub fn read(&mut self, input: &str) -> Result<&str, &str>` (not the mut self) I get the following error:

```
src/gtp/test.rs:47:9: 47:20 error: cannot borrow `interpreter` as immutable because it is also borrowed as mutable [E0502]
src/gtp/test.rs:47         interpreter.quit();
                           ^~~~~~~~~~~
src/gtp/test.rs:37:1: 209:2 note: in this expansion of describe! (defined in src/main.rs)
src/gtp/test.rs:158:28: 158:39 note: previous borrow of `interpreter` occurs here; the mutable borrow prevents subsequent moves, borrows, or modification of `interpreter` until the borrow ends
src/gtp/test.rs:158             let response = interpreter.read("list_commands\n");
                                               ^~~~~~~~~~~
```

Obviously this is easy to fix by wrapping the contents of `it` in another pair of curly braces, but wouldn't it be nice if stainless did that for you? I mean, is there a downside to always doing it like this?

BTW, I'd be willing to have a look at this myself.

**Comment by utkarshkukreti** [comment]
> I mean, is there a downside to always doing it like this?

You won't be able to access variables declared in `it` blocks from the `after_each` hooks.

**Comment by ujh** [comment]
Is this something that should be supported? I mean, coming from Ruby and RSpec I'm totally fine with not being able to access local variables of the test in the after hooks.

**Comment by utkarshkukreti** [comment]
But in RSpec (and probably other Ruby testing frameworks) you can assign instance variables and access those in after hooks. Assigning to local variables is the only way to achieve that in Stainless.

**Comment by ujh** [comment]
But that's a horrible idea, isn't it? The only time I would use an `after_each` would be to tear down something I've set up in a `before_each`.

But actually forbidding this is not totally ideal either that is true.

**Comment by ujh** [comment]
Although, if you *really* needed to do that you could define a `mut` variable in `before_each`. That can be changed in the test then but is also accessible in `after_each`.

**Comment by utkarshkukreti** [comment]
Probably. I've personally never had the need to use `after_each` in Rust (all the cleanup needed was handled by the `Drop` impls).

**Comment by ujh** [comment]
So do you think you would accept a pull request to change the behaviour? I personally would find it more intuitive if the `it` block would be wrapped in a lexical scope. However it may just be that I'm using Rust wrong and this isn't even an issue.

**Comment by ujh** [comment]
OK, I think I'll close this. A proper implementation of `Drop` is much nicer anyway.
