### ISSUE TITLE
Feature request: Give an expected panic message to `failing`

### ISSUE THREAD

**Issue by JohanLorenzo** [reem/stainless#50]
Sometimes, a test is designed to be failing. In this case, it's preferable to make sure we fail for the correct reason.

Would a syntax like this one work @reem ? 
```rust
  failing("expected failure") "this test should pass" {
    panic!("expected failure")
  } 

  failing("expected failure") "this test should fail" {
    panic!("wrong failure")
  } 
```

**Comment by cramertj** [comment]
I just added it and submitted a PR.

**Comment by JohanLorenzo** [comment]
I forgot to say thank you @cramertj and @reem for enabling that feature super quickly :+1:

**Comment by cramertj** [comment]
@JohanLorenzo No problem!
