### ISSUE TITLE
install / usage instructions ?

### ISSUE THREAD

**Issue by grosser** [reem/stainless#51]
Please add some getting started instructions or link to http://bettong.net/2016/03/09/rust-testing-with-stainless 

@reem

**Comment by grosser** [comment]
basically I'm stuck at this ... followed a few other tutorials but that did not work out ... so back to just what's in the readme ... with code stolen from http://bettong.net/2016/03/09/rust-testing-with-stainless/

with plain rust I get this:

```rust
rustc --test hello.rs
hello.rs:56:5: 56:13 error: macro undefined: 'describe!'
hello.rs:56     describe! canvas_renderer {
                ^~~~~~~~
error: aborting due to previous error
```

with cargo test I get that:

```
cargo test
   Compiling stainless v0.1.4
/Users/mgrosser/.cargo/registry/src/github.com-0a35038f75765ae4/stainless-0.1.4/src/lib.rs:1:1: 1:61 error: #[feature] may not be used on the stable release channel
/Users/mgrosser/.cargo/registry/src/github.com-0a35038f75765ae4/stainless-0.1.4/src/lib.rs:1 #![feature(plugin_registrar, quote, rustc_private,const_fn)]
                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `stainless`.

To learn more, run the command again with --verbose.
```

code:

```
pub struct Canvas {
    width: usize,
    height: usize,
    array: Vec<char>
}

impl Canvas {

    pub fn new(width: usize, height: usize, array: Vec<char>) -> Canvas {
        Canvas {
            width: width,
            height: height,
            array: array,
        }
    }

    pub fn array(&self) -> &Vec<char> {
        &self.array
    }
}

pub struct CanvasRenderer<'a> {
    canvas: &'a mut Canvas
}

impl <'a>CanvasRenderer<'a> {
    pub fn new(canvas: &'a mut Canvas) -> CanvasRenderer {
        CanvasRenderer {
            canvas: canvas
        }
    }

    pub fn render_point(&mut self, fill_symbol: char, pos_x: usize, pos_y: usize) {
        let canvas = &mut self.canvas;
        let mut array_to_fill = &mut canvas.array;
        let max_width: usize = canvas.width;
        let max_height: usize = canvas.height;
        let pos_to_draw = pos_x * pos_y;

        if pos_x > max_width || pos_y > max_height {
            panic!("Coordinates are out of array bounds")
        }

        array_to_fill[pos_to_draw] = fill_symbol;

    }
}


#[cfg(test)]

mod tests {
    pub use super::CanvasRenderer;
    pub use super::Canvas;

    describe! canvas_renderer {

        before_each {
            let mut canvas = Canvas {
                width: 10,
                height: 10,
                array: vec!['x';10*10],
            };
        }

        it "should fill given char at given coords" {
            {
                let mut renderer: CanvasRenderer = CanvasRenderer::new(&mut canvas);
                renderer.render_point('x', 3,3);
            }
            assert_eq!('x', canvas.array[3*3]);
        }
    }
}
```

**Comment by ujh** [comment]
Stainless only works with the nightly build of rust. Looking at the error message it seems that you're trying to compile it with a stable version of the compiler.

**Comment by grosser** [comment]
maybe you should put that in the readme ...

**Comment by ujh** [comment]
Yes, the README isn't that good. That's why I wrote the blog post. ;) But I've been meaning to improve the README for a while now.

**Comment by grosser** [comment]
yeah ... blog posts are hard to find and get outdated quickly :)

**Comment by ujh** [comment]
I will do my best. Although only @reem can merge the changes in the end.

**Comment by ujh** [comment]
Is this understandable @grosser? https://github.com/ujh/stainless/tree/improve-readme

**Comment by grosser** [comment]
yes! :heart:

**Comment by grosser** [comment]
tried again with latest rust + stainless and getting the same error ... also the tests in stainless itself are not running ... can you paste what version of rust you are on ?

**Comment by grosser** [comment]
I'm doing `brew install rust --HEAD` to get the latest

**Comment by reem** [comment]
Can you try installing rust using multirust instead? Try:

```sh
brew update
brew uninstall rust
brew install multirust

multirust update

cd my-project
multirust override nightly
cargo test
```

**Comment by grosser** [comment]
that works ...

but that means it's broken with the latest rust ... or the `brew install rust` is broken ...

**Comment by ujh** [comment]
Cool. Sorry for not getting back to you. I quickly checked yesterday and it had worked for me as well. I install the latest nightly using the Rust installer (shell script) from the homepage. 

BTW, big fan of parallel_tests :)

**Comment by grosser** [comment]
Thx!

I'll just close this ... still findable via search I guess ...

**Comment by ujh** [comment]
I tried with the latest nightly from a day or two ago. So it's more likely that the homebrew version in old or broken.

**Comment by grosser** [comment]
now on rust 1.14 and this is still broken ...

```
error[E0554]: #[feature] may not be used on the stable release channel
```

so the readme needs to say 'use nightly' ... or we should remove the `feature` ?

**Comment by grosser** [comment]
so I guess the answer is use nightly: https://github.com/SkylerLipthay/interpolate_idents/issues/13
... should still add this info to the readme ...

**Comment by ujh** [comment]
Yes, it requires nightly. See the bold sentence at the beginning of the readme. ;)

**Comment by grosser** [comment]
You expect anyone to read a sentence starting with "Note that " ? :D
-> "REQUIRED RUST NIGHTLY"

**Comment by ujh** [comment]
Quite frankly I'm less and less convinced that a compiler plugin is the way to go. The rules of when and where a variable is accessible are different from standard Rust (stuff in before is visible in the tests) and it breaks in weird ways. I think it would be worth exploring how far you can get with standard built in tools. Maybe some day I'll get around to exploring this.

**Comment by grosser** [comment]
Yeah, though about picking it up again and then ended up writing tests in
ruby :D

FYI https://github.com/grosser/preoomkiller
