### ISSUE TITLE
duplicat test output

### ISSUE THREAD

**Issue by grosser** [reem/stainless#55]
https://github.com/grosser/hello-rust

```
rustc 1.9.0-nightly (d5a91e695 2016-03-26)
cargo test
running 1 test
test tests::stainless::can_use_HashMap ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests t

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

**Comment by ujh** [comment]
That's not a stainless issue as it uses the standard Rust test runner under the hood. I thin the output also isn't duplicated. The second block are doc tests which I don't know much about. IIRC they're executable code that's part of doc strings.

**Comment by grosser** [comment]
thx for the clarification ... I though it's stainless somehow running it's own test runner :)
