### ISSUE TITLE
Help maintaining this crate needed?

### ISSUE THREAD

**Issue by ujh** [reem/stainless#57]
Hey there,

I was wondering if there's anything we the users of this crate can do to help you with the maintenance of this crate @reem. I'd love to help but obviously I can't close outdated issues (like #43) or merge pull requests. If this is something you're interested in we can of course also discuss this over email if you prefer (contact@urbanhafner.com).

Thanks for creating this awesome tool and like I said, I'd love to help out to make it even better.

**Comment by reem** [comment]
Hey, I would love help with maintenance. I've added you as a contributor to the repo, feel free to merge PRs, close issues, make fixes, etc.

**Comment by ujh** [comment]
Great! Thank you!
