### ISSUE TITLE
Windows 10 cargo test fails - nightly 1.13.0

### ISSUE THREAD

**Issue by xetra11** [reem/stainless#64]
Hello guys!

I don't know if this is an issue of stainless or an allover issue with Windowns + Rust.
I'm trying IntelliJ-Rust and tried to "cargo test" my project I created under Linux.

This is what the log says:

> C:\Users\XXX\.cargo\bin\cargo.exe test --verbose
>    Compiling stainless v0.1.4
>      Running `C:\Users\XXX\.cargo\bin\rustc.exe C:\Users\XXX\.cargo\registry\src\github.com-1ecc6299db9ec823\stainless-0.1.4\src/lib.rs --crate-name stainless --crate-type dylib -C prefer-dynamic -g -C metadata=57baff5f4305cdf0 -C extra-filename=-57baff5f4305cdf0 --out-dir "C:\Users\XXX\XXX\workspace\Software Development\renderay.rs\target\debug\deps" --emit=dep-info,link -L "dependency=C:\Users\XXX\XXX\workspace\Software Development\renderay.rs\target\debug\deps" --cap-lints allow`
> error[E0412]: type name `ast::TokenTree` is undefined or not in scope
>   --> C:\Users\XXX\.cargo\registry\src\github.com-1ecc6299db9ec823\stainless-0.1.4\src\describe.rs:60:47
>    |
> 60 |                 name: ast::Ident, tokens: Vec<ast::TokenTree>) -> Box<base::MacResult + 'a> {
>    |                                               ^^^^^^^^^^^^^^ undefined or not in scope
>    |
>    = help: you can import several candidates into scope (`use ...;`):
>    = help:   `syntax::ext::proc_macro_shim::prelude::TokenTree`
>    = help:   `syntax::syntax::ext::proc_macro_shim::prelude::TokenTree`
>    = help:   `syntax::tokenstream::TokenTree`
> 
> error[E0277]: the trait bound `syntax::ext::base::IdentMacroExpander: std::marker::Sized` is not satisfied
>    --> C:\Users\XXX\.cargo\registry\src\github.com-1ecc6299db9ec823\stainless-0.1.4\src/lib.rs:100:36
>     |
> 100 |         syntax::ext::base::IdentTT(Box::new(describe), None, false)
>     |                                    ^^^^^^^^
>     |
>     = note: `syntax::ext::base::IdentMacroExpander` does not have a constant size known at compile-time
>     = note: required by `std::boxed::<impl Box<T>>::new`
> 
> error: aborting due to previous error
> 
> error: Could not compile `stainless`.
> 
> Caused by:
>   Process didn't exit successfully: `C:\Users\XXX\.cargo\bin\rustc.exe C:\Users\XXX\.cargo\registry\src\github.com-1ecc6299db9ec823\stainless-0.1.4\src/lib.rs --crate-name stainless --crate-type dylib -C prefer-dynamic -g -C metadata=57baff5f4305cdf0 -C extra-filename=-57baff5f4305cdf0 --out-dir C:\Users\XXX\XXX\workspace\Software Development\renderay.rs\target\debug\deps --emit=dep-info,link -L dependency=C:\Users\XXX\XXX\workspace\Software Development\renderay.rs\target\debug\deps --cap-lints allow` (exit code: 101)
> 
> Process finished with exit code 101
> 

rustup nightly:
 **nightly-x86_64-pc-windows-msvc unchanged - rustc 1.13.0-nightly (490189634 2016-08-20**)

**Comment by ujh** [comment]
Oh, that's not nice! I'll see if I can get an Appveyor build setup so that we can track this. It's possible that it's been broken for a long time. 😁

**Comment by xetra11** [comment]
I tried to build on Travis CI with the .yml you guys posted there. Sadly doesnt work with nightly 1.13.0 it seems. I tried to let my .travis.yml run with nightly 1.11.0 but no success yet. Can't find a way how to tell Travis CI to run with a specific nightly version - if thats possible with rustup anyway?

**Comment by xetra11** [comment]
Sorry my friend but it seems the bug was with me. I though declaring the version as "*" will update stainless automatically. Wasn't the case so I was still running on version "0.1.4" instead of "0.1.6"...

Now it works fine! Sorry for the wasted time!

**Comment by ujh** [comment]
No worries, now we know that we should set up a Windows build as well. :)
