### ISSUE TITLE
`bench` does not have access to `before_each`

### ISSUE THREAD

**Issue by ysimonson** [reem/stainless#69]
Anything placed into the `before_each` block doesn't seem to affect to `bench` blocks. I managed to get around this by just copy-pasting what was in `before_each` into each `bench` block.

For context, this is on stainless 0.1.7, and rustc version `1.13.0-nightly (1fca1ab0e 2016-09-10)`.

**Comment by ujh** [comment]
Yes, that's a current limitation of the benchmarks. It's documented in the README. 😁 It's on my list of things to add it but I'm not quite sure yet how do do it. I've collected my thoughts on the issue in #70.

**Comment by ysimonson** [comment]
Sorry I missed that!

**Comment by ujh** [comment]
No worries. It tripped me up at the beginning as well.
