### ISSUE TITLE
Before and after subblocks don't work 

### ISSUE THREAD

**Issue by NotBad4U** [reem/stainless#78]
The `before` and `after` subblocks seem to doesn't work. They are parsed but never call during the execution.
``` rust
#![feature(plugin)]
#![plugin(stainless)]

describe! addition {
    before {
        println!("In before");
    }

    before_each {
        println!("in before each");
        let x = 5;
        let y = 6;
    }

    it "should add 5 and 6 together" {
        assert_eq!(x + y, 11);
    }

    after_each {
        println!("in after each");
    }

    after {
        println!("In after");
    }
}

```
That give me this result : 
```
cargo test -- --nocapture
.....
running 1 test
in before each
in after each
test addition::should_add_5_and_6_together ... ok
```

``` bash
$ rustc --version
rustc 1.17.0-nightly (c0b7112ba 2017-03-02)

[dependencies]
stainless = "0.1.10"

```

**Comment by ujh** [comment]
You're right! I didn't even know `before` and `after` where being parsed. They're not mentioned anywhere in the documentation so I will just remove them to avoid confusuin.

**Comment by NotBad4U** [comment]
Why you want to remove this two subblocks ? They can be usefull in many case like starting a server before to run the tests.

**Comment by utkarshkukreti** [comment]
@NotBad4U these two were never actually implemented. They were just parsed and ignored. As far as I know, it's not easy to implement this feature with Rust's default test runner.

**Comment by NotBad4U** [comment]
@utkarshkukreti Okai I understand, thanks for the response :smile: . So I think you can close the issue.
